"use server";

import { revalidatePath } from "next/cache";
import { getUserSession } from "@/lib/auth";
import { db } from "@/server/db";

export interface UpiIdItem {
  id: string;
  label: string;
  vpa: string;
  isPrimary: boolean;
  createdAt: Date;
}

export interface PaymentLinkItem {
  id: string;
  slug: string;
  vpa: string;
  payeeName: string;
  amount: number | null;
  note: string | null;
  views: number;
  status: string;
  workspaceId: string | null;
  createdAt: Date;
}

/**
 * Gets all saved UPI IDs for the current user.
 */
export async function getUserUpiIds(): Promise<UpiIdItem[]> {
  try {
    const user = await getUserSession();
    if (!user?.id) return [];

    const upiIds = await db.userUpiId.findMany({
      where: { userId: user.id },
      orderBy: [{ isPrimary: "desc" }, { createdAt: "desc" }],
    });

    return upiIds.map((item) => ({
      id: item.id,
      label: item.label,
      vpa: item.vpa,
      isPrimary: item.isPrimary,
      createdAt: item.createdAt,
    }));
  } catch (error) {
    console.error("Error fetching UPI IDs:", error);
    return [];
  }
}

/**
 * Creates or saves a new UPI VPA for the user.
 */
export async function createUserUpiId(input: {
  label: string;
  vpa: string;
  isPrimary?: boolean;
}): Promise<{ success: boolean; data?: UpiIdItem; error?: string }> {
  try {
    const user = await getUserSession();
    if (!user?.id) throw new Error("Unauthorized");

    const vpaClean = input.vpa.trim().toLowerCase();
    if (!vpaClean.includes("@") || vpaClean.length < 4) {
      throw new Error("Invalid UPI VPA address (e.g. username@bank)");
    }

    if (input.isPrimary) {
      await db.userUpiId.updateMany({
        where: { userId: user.id, isPrimary: true },
        data: { isPrimary: false },
      });
    }

    const created = await db.userUpiId.create({
      data: {
        label: input.label.trim(),
        vpa: vpaClean,
        isPrimary: input.isPrimary ?? false,
        userId: user.id,
      },
    });

    revalidatePath("/[workspaceId]/upi", "page");
    return {
      success: true,
      data: {
        id: created.id,
        label: created.label,
        vpa: created.vpa,
        isPrimary: created.isPrimary,
        createdAt: created.createdAt,
      },
    };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
}

/**
 * Deletes a saved UPI VPA.
 */
export async function deleteUserUpiId(
  id: string,
): Promise<{ success: boolean; error?: string }> {
  try {
    const user = await getUserSession();
    if (!user?.id) throw new Error("Unauthorized");

    await db.userUpiId.delete({
      where: { id, userId: user.id },
    });

    revalidatePath("/[workspaceId]/upi", "page");
    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
}

/**
 * Gets payment links generated by the user.
 */
export async function getPaymentLinks(
  workspaceId?: string,
): Promise<PaymentLinkItem[]> {
  try {
    const user = await getUserSession();
    if (!user?.id) return [];

    const links = await db.paymentLink.findMany({
      where: {
        userId: user.id,
        ...(workspaceId ? { workspaceId } : {}),
      },
      orderBy: { createdAt: "desc" },
    });

    return links.map((link) => ({
      id: link.id,
      slug: link.slug,
      vpa: link.vpa,
      payeeName: link.payeeName,
      amount: link.amount ? link.amount.toNumber() : null,
      note: link.note,
      views: link.views,
      status: link.status,
      workspaceId: link.workspaceId,
      createdAt: link.createdAt,
    }));
  } catch (error) {
    console.error("Error fetching payment links:", error);
    return [];
  }
}

/**
 * Generates a new shareable payment link with unique slug.
 */
export async function createPaymentLink(input: {
  vpa: string;
  payeeName: string;
  amount?: number;
  note?: string;
  workspaceId?: string;
}): Promise<{ success: boolean; data?: PaymentLinkItem; error?: string }> {
  try {
    const user = await getUserSession();
    if (!user?.id) throw new Error("Unauthorized");

    const vpaClean = input.vpa.trim().toLowerCase();
    if (!vpaClean.includes("@")) {
      throw new Error("Invalid UPI VPA address");
    }

    // Generate random friendly 8-char slug
    const slug = Math.random().toString(36).substring(2, 10);

    const link = await db.paymentLink.create({
      data: {
        slug,
        vpa: vpaClean,
        payeeName: input.payeeName.trim(),
        amount: input.amount && input.amount > 0 ? input.amount : null,
        note: input.note ? input.note.trim() : null,
        workspaceId: input.workspaceId ?? null,
        userId: user.id,
      },
    });

    if (input.workspaceId) {
      revalidatePath(`/${input.workspaceId}/upi`);
    }

    return {
      success: true,
      data: {
        id: link.id,
        slug: link.slug,
        vpa: link.vpa,
        payeeName: link.payeeName,
        amount: link.amount ? link.amount.toNumber() : null,
        note: link.note,
        views: link.views,
        status: link.status,
        workspaceId: link.workspaceId,
        createdAt: link.createdAt,
      },
    };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
}

/**
 * Public resolver for a payment link by slug. Increments view counter.
 */
export async function getPublicPaymentLink(slug: string) {
  try {
    const link = await db.paymentLink.findUnique({
      where: { slug },
    });

    if (!link) return null;

    // Increment view counter non-blockingly
    await db.paymentLink
      .update({
        where: { id: link.id },
        data: { views: { increment: 1 } },
      })
      .catch(() => null);

    return {
      id: link.id,
      slug: link.slug,
      vpa: link.vpa,
      payeeName: link.payeeName,
      amount: link.amount ? link.amount.toNumber() : null,
      note: link.note,
      status: link.status,
      createdAt: link.createdAt,
    };
  } catch (error) {
    console.error("Error fetching public payment link:", error);
    return null;
  }
}

/**
 * Marks a payment link as RECEIVED and automatically records an INCOME transaction.
 */
export async function markPaymentReceived(input: {
  linkId: string;
  financialAccountId: string;
  workspaceId: string;
  amountReceived?: number;
}): Promise<{ success: boolean; error?: string }> {
  try {
    const user = await getUserSession();
    if (!user?.id) throw new Error("Unauthorized");

    const link = await db.paymentLink.findFirst({
      where: { id: input.linkId, userId: user.id },
    });
    if (!link) throw new Error("Payment link not found");

    const amount =
      input.amountReceived ?? (link.amount ? link.amount.toNumber() : 0);
    if (amount <= 0) {
      throw new Error(
        "Amount must be greater than 0 to record an income transaction",
      );
    }

    // Run in transaction: mark link RECEIVED + create INCOME transaction + update account balance
    await db.$transaction(async (tx) => {
      await tx.paymentLink.update({
        where: { id: link.id },
        data: { status: "RECEIVED" },
      });

      await tx.transaction.create({
        data: {
          type: "INCOME",
          amount,
          description: `UPI: from ${link.vpa}${link.note ? ` (${link.note})` : ""}`,
          category: "salary", // or freelance/other-income
          date: new Date(),
          workspaceId: input.workspaceId,
          financialAccountId: input.financialAccountId,
          status: "COMPLETED",
        },
      });

      await tx.financialAccount.update({
        where: { id: input.financialAccountId },
        data: {
          balance: { increment: amount },
        },
      });
    });

    revalidatePath(`/${input.workspaceId}/upi`);
    revalidatePath(`/${input.workspaceId}/dashboard`);
    revalidatePath(`/${input.workspaceId}/transactions`);
    revalidatePath(`/${input.workspaceId}/accounts`);

    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
}
